name: home-listing-laos

services:
  # db:
  #   image: mariadb:lts-ubi9
  #   container_name: db
  #   restart: unless-stopped
  #   ports:
  #   - "3306:3306"
  #   env_file: .env
  #   volumes:
  #   - dbdata:/var/lib/mysql
  #   networks:
  #   - app-internal-network

  wordpress:
    # depends_on:
    # - db
    image: wordpress:6.6.2-php8.3-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
    - WORDPRESS_DB_HOST=db:3306
    volumes:
    - wordpress:/var/www/html
    networks:
    - app-internal-network

  webserver:
    depends_on:
    - wordpress
    image: nginx:1.27.1-alpine-slim
    container_name: webserver
    restart: unless-stopped
    ports:
    - "80:80"
    volumes:
    - wordpress:/var/www/html
    - ./nginx-conf:/etc/nginx/conf.d
    - certbot-etc:/etc/letsencrypt
    networks:
    - app-internal-network
    # - host-network
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 120s
    #   resources:
    #     limits:
    #       cpus: '0.001'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.0001'
    #       memory: 20M


  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email faccomichele@gmail.com --agree-tos --no-eff-email --staging -d nubicu.eu -d localtest.nubicu.eu

volumes:
  certbot-etc:
  wordpress:
    # external: true
    # name: actual-name-of-volume
  # dbdata:

networks:
  app-internal-network:
    driver: bridge
  # host-network:
  #   driver: host